### ISSUE TITLE
There is no way to set the large icon on Android

### ISSUE THREAD

**Issue by juanrobertodeanda** [CrossGeeks/AzurePushNotificationPlugin#10]
It turns out that Android uses different notification icons for the status bar and for the drawer notification panel. `NotificationCompat.Builder` has  `setSmallIcon` method and `setLargeIcon` method to handle each case, but AzurePushNotificationPlugin only allows to set `IconResource` property which is mapped to `setSmallIcon` as seen [here](https://github.com/CrossGeeks/AzurePushNotificationPlugin/blob/b63d5bae78d8b461cc0e82e2efa18f613d78e720/src/Plugin.AzurePushNotification.Android/DefaultPushNotificationHandler.cs#L276). It would be great too have a way to set the large icon too.  

Thanks

**Comment by rdelrosario** [comment]
Latest version now supports large icon
