### ISSUE TITLE
 Invalid notification (no valid small icon) 

### ISSUE THREAD

**Issue by muhammetsahin** [CrossGeeks/AzurePushNotificationPlugin#14]
Hi,

Im using Plugin.AzurePushNotification v 1.1.0 and

Xamarin forms v 3.1.0.69772

![image](https://user-images.githubusercontent.com/2045788/45233132-75934300-b2da-11e8-9cb7-86b7581222a9.png)
And im already added app cion 

![image](https://user-images.githubusercontent.com/2045788/45233146-85128c00-b2da-11e8-8910-d3e816c16cfc.png)

But i've got an error.

Could you help me?

Thanks

**Comment by matei-tm** [comment]
In AndroidManifest.xml set an android:icon attribute that point to a valid icon resource

```xml
<application android:label="your_great_application_label" android:icon="@drawable/icon">
```

**Comment by matei-tm** [comment]
Alternatively you may set a custom icon for the notification

```C#
    [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();

            AzurePushNotificationManager.IconResource = Resource.Drawable.ic_push;
....
```
