### ISSUE TITLE
isRegisteredForRemoteNotifications

### ISSUE THREAD

**Issue by aherrick** [CrossGeeks/AzurePushNotificationPlugin#19]
Is there any cross platform way to detect if the user has already registered for push notifications? I know Apple has `isRegisteredForRemoteNotifications`

This would be handy on App load to check to see if they've registered somewhere else in the App, if so call register again so a new token will always update.

**Comment by rdelrosario** [comment]
Just added this in latest beta version:

https://www.nuget.org/packages/Plugin.AzurePushNotification/2.0.1-beta

CrossAzurePushNotification.Current.IsEnabled
