### ISSUE TITLE
Not Support All the Architecture in IOS

### ISSUE THREAD

**Issue by Codeadmire** [CrossGeeks/AzurePushNotificationPlugin#2]
Hi,
I not able to release the app with following build like ARMv7+ARMv7s+ARM64 .
can you please help to solve the issue.

I am getting the below error.

MT5209: Error: ignoring file , file was built for armv7 which is not the architecture being linked (armv7s): /obj/iPhone/Release/mtouch-cache/armv7/System.Core.dll.o  Native linking

MT5209: Error: file is universal (4 slices) but does not contain a(n) armv7s slice: /obj/iPhone/Release/mtouch-cache/WindowsAzureMessaging.framework/WindowsAzureMessaging file '/obj/iPhone/Release/mtouch-cache/WindowsAzureMessaging.framework/WindowsAzureMessaging' for architecture armv7s  Native linking
Please help me to resolve the issue

Thanks,
Tamilmani

**Comment by rdelrosario** [comment]
This doesn't seem to be an issue of the plugin. You are referencing the Windows Azure Messaging package not the plugin on this error.

**Comment by gmbertolotto** [comment]
Same error, but  on my project there is no reference to the Windows Azure Messaging package. If I take off your plugin it's all ok
