### ISSUE TITLE
Xamarin Forms Android does not receive notification when app is killed.

### ISSUE THREAD

**Issue by RickB864** [CrossGeeks/AzurePushNotificationPlugin#21]
Android works well when in foreground or background. Does not receive notification when the app is in the killed state. I have compiled the app in release mode and removed all references to system.diagnostics.debug within my code.

I have the following permissions  in Manifest.
`<uses-permission android:name="android.permission.WAKE_LOCK" />
  <permission
      android:name="co.my.packagename.permission.C2D_MESSAGE"
      android:protectionLevel="signature" />
  <uses-permission android:name="co.my.packagename.C2D_MESSAGE" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="android.permission.VIBRATE" />`

and the following receiver:
 `<receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
        android:exported="false" />
    <receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="${applicationId}" />
      </intent-filter>
    </receiver>`

**Comment by tomasjuricek** [comment]
Try to add that permissions:

[assembly: Permission(Name = "@PACKAGE_NAME@.permission.C2D_MESSAGE", ProtectionLevel = Android.Content.PM.Protection.Signature)]
[assembly: UsesPermission(Name = "@PACKAGE_NAME@.permission.C2D_MESSAGE")]

**Comment by RickB864** [comment]
the above permission did the trick. Thanks.
