### ISSUE TITLE
Support for Firebase 60.1142.1

### ISSUE THREAD

**Issue by RickB864** [CrossGeeks/AzurePushNotificationPlugin#25]
I need to upgrade several Xamarin.Firebase packages from 60.1142.0 to 60.1142.1 and this plugin is prohibiting me from upgrading. Any timeline to release a version that is compatible with .1?

**Comment by rdelrosario** [comment]
Support is available on beta version: 

https://www.nuget.org/packages/Plugin.AzurePushNotification/2.0.1-beta
