### ISSUE TITLE
Update nuspec

### ISSUE THREAD

**Issue by mclillill** [CrossGeeks/AzurePushNotificationPlugin#3]
> Severity	Code	Description	Project	File	Line	Suppression State
> Warning	NU1608	Detected package version outside of dependency constraint: Plugin.AzurePushNotification 1.1.0 requires Xamarin.Firebase.Messaging (= 60.1142.0) but version Xamarin.Firebase.Messaging 60.1142.1 was resolved.	

Thank you for your work!

**Comment by rdelrosario** [comment]
Do you know what this update adds?

**Comment by mclillill** [comment]
No idea.

**Comment by ShahmanTeh** [comment]
any updates to this? I'm currently using latest xamarin.forms.maps which used 60.1142.1, and I am thinking about using this plugins.

**Comment by rdelrosario** [comment]
Just created a pre-release with this:

https://www.nuget.org/packages/Plugin.AzurePushNotification/1.2.0-pre
