### ISSUE TITLE
Package reference conflict with newer version on google services

### ISSUE THREAD

**Issue by dationguyen** [CrossGeeks/AzurePushNotificationPlugin#30]
https://github.com/CrossGeeks/AzurePushNotificationPlugin/blob/b05dcb4b0f45406acdb6da37e96348a04eabe59c/nuget/Plugin.nuspec#L23

Please remove [ ] from the google play services version in nuspec

**Comment by rdelrosario** [comment]
Should be fixed on beta version: 

https://www.nuget.org/packages/Plugin.AzurePushNotification/2.0.1-beta
