### ISSUE TITLE
Java.Lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by IeuanWalker** [CrossGeeks/AzurePushNotificationPlugin#31]
Getting the following error when running the android build - 
`Java.Lang.NoClassDefFoundError: 'Failed resolution of: Lcom/google/android/gms/common/internal/zzbp;'`

And this is from the logs -
`11-08 11:09:06.309 E/AndroidRuntime(16071): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbp" on path: DexPathList[[zip file "/data/app/uk.gov.cardiff.CardiffGov.Android-Me5H2YwmgUAAxym26dJW2w==/base.apk"],nativeLibraryDirectories=[/data/app/uk.gov.cardiff.CardiffGov.Android-Me5H2YwmgUAAxym26dJW2w==/lib/arm64, /data/app/uk.gov.cardiff.CardiffGov.Android-Me5H2YwmgUAAxym26dJW2w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]`

**Comment by rdelrosario** [comment]
This doesn't seem to be related to the plugin

**Comment by IeuanWalker** [comment]
@rdelrosario  Pretty sure it is, all i done was add the plugin.
Was building and running fine before hand.

When i have time i'll create a test project and see if i get the same result

**Comment by rdelrosario** [comment]
Try latest version just published a new one.
