### ISSUE TITLE
Please update to support iOS 13

### ISSUE THREAD

**Issue by gmbertolotto** [CrossGeeks/AzurePushNotificationPlugin#32]
I used your plugin in my iOS app and everything worked fine so far. Unfortunately, with the version of iOS 13 notifications are no longer working.
I see that the source file has already changed but the Nuget package does not contain the corrections.
Could you please update the plugin? Thanks

**Comment by thetechrasta** [comment]
Does this currently support iOS 13 ?

**Comment by gmbertolotto** [comment]
If the app is compiled using Xcode 10 it's ok, but with Xcode 11 it will not run on iOS 13 devices.

**Comment by rdelrosario** [comment]
Support is available on beta version: 

https://www.nuget.org/packages/Plugin.AzurePushNotification/2.0.1-beta
