### ISSUE TITLE
Xamarin.Android

### ISSUE THREAD

**Issue by gamidon** [CrossGeeks/AzurePushNotificationPlugin#6]
I have created a new project and I cannot include this plugin.  It requires packages that are not supported by the latest released or pre-released versions of Xamarin.Forms.  
 How do I  resolve this?

Appreciate your efforts. Greg

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 TestCrossGeeks2.Android -> TestCrossGeeks2 -> Plugin.AzurePushNotification 1.1.0 -> Xamarin.Firebase.Messaging 60.1142.0 -> Xamarin.GooglePlayServices.Basement 60.1142.0 -> Xamarin.Android.Support.Compat (>= 26.0.2) 
 TestCrossGeeks2.Android -> Xamarin.Forms 2.5.1.340284-pre2 -> Xamarin.Android.Support.Design 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

**Comment by gamidon** [comment]
I understand what you are saying, the issue is that I cannot do it.  The install gets reverted.  Xamarin Forms is currently locked on 25.4.0.2  I am using the latest preview and it doesn't support 26.0.2  See below I put in the information from xamarin forms dependencies.   I Sincerely appreciate your input.  

I just started a new project xamarin forms and tried to install your package, it installs into iOS but fails to install into Android.   


From: https://www.nuget.org/packages/Xamarin.Forms/2.5.0.121934

Xamarin.Forms 2.5.0.121934
MonoAndroid 7.1
Xamarin.Android.Support.Design (>= 25.4.0.2) 
Xamarin.Android.Support.v4 (>= 25.4.0.2) 
Xamarin.Android.Support.v7.AppCompat (>= 25.4.0.2) 
Xamarin.Android.Support.v7.CardView (>= 25.4.0.2) 
Xamarin.Android.Support.v7.MediaRouter (>= 25.4.0.2)

**Comment by gamidon** [comment]
I have isolated it to the Xamarin.Forms.Maps   I ran your sample, tried to install Xamarin.Forms.Maps and I cannot get that to install, it reverts it back out exactly how my app (with maps already) reverts out this plugin.  How can I get both to coexist?

Thanks,
Greg

**Comment by rdelrosario** [comment]
The only thing you can do is installing:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.3

**Comment by rdelrosario** [comment]
Unfortunately, you can't do much. I started this plugin using Google Play Services latest version, Maps is using 42.1021.1 and haven't upgraded the Google play package in a while. Until they upgrade it both can't coexist
