### ISSUE TITLE
Java.Util.MissingFormatArgumentException when using parameters in android localization string

### ISSUE THREAD

**Issue by michelmoorlag** [CrossGeeks/AzurePushNotificationPlugin#9]
I have followed all documentation to the letter and implemented the the plugin on android succesfully. Now I want to localize my messages and I followed the instructions to add localization without parameters. This works fine and message and title gets translated. Now I followed the documentation to add parameters. 
This is my default values.xml:

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
<string name="notification_title_string">Hello %1$s</string>
<string name="notification_message_string">This is a message for %1$s</string>
</resources>
```

Now I send a test message like the example:

```
{
    "data": {
          "title_loc_key" : "notification_title_string",
          "body_loc_key" : "notification_message_string",
          "title_loc_args" : ["Dominican Republic"],
          "body_loc_args" : ["Rendy"]
     },
     "priority": "high"
}
```

The breakpoint in 
```
            CrossAzurePushNotification.Current.OnNotificationReceived += (s, p) =>
            {


            };
```
gets hit but after that I get a unhandeled: "_Java.Util.MissingFormatArgumentException : Format specifier: 1$s_" and the app terminates. 
I am using X.F. version 3.0.0.530893 with the v27.0.2  android support libs and version 1.1.0 of the Plugin.AzurePushNotification on a Android 6 phone.

If helpfull I can create a simple sample application to demonstrate the issue?

**Comment by rdelrosario** [comment]
Fixed on latest release.
